version: '2'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "webapp"
    ports:
      - "3306:3306"

  redis:
    image: redis:3.2.6
    ports:
      - "6379:6379"

